In [4]:
import pandas as pd

customers = pd.read_csv("data/olist_customers_dataset.csv")
oitems = pd.read_csv("data/olist_order_items_dataset.csv")
opayments = pd.read_csv("data/olist_order_payments_dataset.csv")
orders = pd.read_csv("data/olist_orders_dataset.csv")
products = pd.read_csv("data/olist_products_dataset.csv")
geolocation = pd.read_csv("data/olist_geolocation_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [5]:
oitems.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
opayments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [9]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [10]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [11]:
print("Orders shape:", orders.shape)

Orders shape: (99441, 8)

In [12]:
print("Items shape:", oitems.shape)
print("Payments shape:", opayments.shape)
print("Customers shape:", customers.shape)
print("Products shape:", products.shape)

Items shape: (112650, 7)
Payments shape: (103886, 5)
Customers shape: (99441, 5)
Products shape: (32951, 9)

In [13]:
print("\nOrders columns:\n", orders.columns)

Orders columns:
 Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [14]:
print("\nItems columns:\n", oitems.columns)
print("\nPayments columns:\n", opayments.columns)
print("\nCustomers columns:\n", customers.columns)
print("\nProducts columns:\n", products.columns)

Items columns:
 Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

Payments columns:
 Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

Customers columns:
 Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

Products columns:
 Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [16]:
print("\nMissing values in customers:\n", customers.isnull().sum())
print("\nMissing values in orders:\n", orders.isnull().sum())
print("\nMissing values in items:\n", oitems.isnull().sum())
print("\nMissing values in payments:\n", opayments.isnull().sum())
print("\nMissing values in products:\n", products.isnull().sum())

Missing values in customers:
 customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Missing values in orders:
 order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Missing values in items:
 order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Missing values in payments:
 order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Missing values in products:
 product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [17]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [18]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

oitems['shipping_limit_date'] = pd.to_datetime(oitems['shipping_limit_date'])

In [19]:
print(orders.dtypes)
print(oitems.dtypes)

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [20]:
orders['delivery_time_days'] = (
    orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
).dt.days # this is to know total delivery days

In [21]:
orders['is_delayed'] = (
    orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date']
) # this is to know whether the delivery was late or not for customer satisfaction

In [22]:
oitems['total_item_value'] = oitems['price'] + oitems['freight_value']

In [23]:
order_value = oitems.groupby('order_id')['total_item_value'].sum().reset_index()
order_value.rename(columns={'total_item_value': 'order_total_value'}, inplace=True)

In [24]:
orders = orders.merge(order_value, on='order_id', how='left') # the entire process was to have total revenue for each order

In [25]:
print(orders[['delivery_time_days', 'is_delayed', 'order_total_value']].head())

   delivery_time_days  is_delayed  order_total_value
0                 8.0       False              38.71
1                13.0       False             141.46
2                 9.0       False             179.12
3                13.0       False              72.20
4                 2.0       False              28.62

In [26]:
final_df = orders.merge(customers, on='customer_id', how='left')

In [27]:
payment_summary = opayments.groupby('order_id')['payment_value'].sum().reset_index()

final_df = final_df.merge(payment_summary, on='order_id', how='left')

In [30]:
print(final_df.shape)

(99441, 16)

In [32]:
print(final_df.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_time_days', 'is_delayed', 'order_total_value',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'payment_value'],
      dtype='object')

In [33]:
print(final_df.head())

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date  delivery_time_days  is_delayed  \
0                    2017-10-18                 8.0       False
1                    2018-08-13                13.0       False
2                    2018-09-04                 9.0       False
3                    2017-12-15                13.0       False
4                    2018-02-26                 2.0       False

   order_total_value                customer_unique_id  \
0              38.71  7c396fd4830fd04220f754e42b4e5bff
1             141.46  af07308b275d755c9edb36a90c618231
2             179.12  3a653a41f6f9fc3d2a113cf8398680e8
3              72.20  7c142cf63193a1473d2e66489a9ae977
4              28.62  72632f0f9dd73dfee390c9b22eb56dd6

   customer_zip_code_prefix            customer_city customer_state  \
0                      3149                sao paulo             SP
1                     47813                barreiras             BA
2                     75265               vianopolis             GO
3                     59296  sao goncalo do amarante             RN
4                      9195              santo andre             SP

   payment_value
0          38.71
1         141.46
2         179.12
3          72.20
4          28.62

In [26]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)

In [28]:
import sys
print(sys.executable)

/opt/anaconda3/envs/project_env/bin/python

In [29]:
import sys
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp310-cp310-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/envs/project_env/lib/python3.10/site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.48-cp310-cp310-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 14.2 MB/s  0:00:00
Downloading psycopg2_binary-2.9.11-cp310-cp310-macosx_11_0_arm64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 38.2 MB/s  0:00:00
Installing collected packages: sqlalchemy, psycopg2-binary
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [psycopg2-binary]
Successfully installed psycopg2-binary-2.9.11 sqlalchemy-2.0.48

In [1]:
from sqlalchemy import create_engine

In [2]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:ksrWSUsql1995+@localhost:5432/erp_db")

In [38]:
final_df.to_sql(
    "orders_data",
    engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

9441